//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCI_Fudbalski_Klub {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCI_Fudbalski_Klub.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistencije.
        /// </summary>
        internal static string asist {
            get {
                return ResourceManager.GetString("asist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj.
        /// </summary>
        internal static string broj {
            get {
                return ResourceManager.GetString("broj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona.
        /// </summary>
        internal static string brtel {
            get {
                return ResourceManager.GetString("brtel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        internal static string conf {
            get {
                return ResourceManager.GetString("conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porazi.
        /// </summary>
        internal static string def {
            get {
                return ResourceManager.GetString("def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Briši.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neriješeno.
        /// </summary>
        internal static string draws {
            get {
                return ResourceManager.GetString("draws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golovi.
        /// </summary>
        internal static string gol {
            get {
                return ResourceManager.GetString("gol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primljeno.
        /// </summary>
        internal static string gr {
            get {
                return ResourceManager.GetString("gr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postignuto.
        /// </summary>
        internal static string gs {
            get {
                return ResourceManager.GetString("gs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string insert {
            get {
                return ResourceManager.GetString("insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        internal static string jezik {
            get {
                return ResourceManager.GetString("jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        internal static string jmb {
            get {
                return ResourceManager.GetString("jmb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liga.
        /// </summary>
        internal static string league {
            get {
                return ResourceManager.GetString("league", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi se.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napusti.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        internal static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odigrao.
        /// </summary>
        internal static string played {
            get {
                return ResourceManager.GetString("played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odigrano.
        /// </summary>
        internal static string playedGames {
            get {
                return ResourceManager.GetString("playedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igrači.
        /// </summary>
        internal static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija.
        /// </summary>
        internal static string poz {
            get {
                return ResourceManager.GetString("poz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži....
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži po imenu.
        /// </summary>
        internal static string searchByName {
            get {
                return ResourceManager.GetString("searchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži po sezoni.
        /// </summary>
        internal static string searchBySeason {
            get {
                return ResourceManager.GetString("searchBySeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sezona.
        /// </summary>
        internal static string season {
            get {
                return ResourceManager.GetString("season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistike.
        /// </summary>
        internal static string stat {
            get {
                return ResourceManager.GetString("stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        internal static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tim.
        /// </summary>
        internal static string team {
            get {
                return ResourceManager.GetString("team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string tema {
            get {
                return ResourceManager.GetString("tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugovor Do.
        /// </summary>
        internal static string ugovorDo {
            get {
                return ResourceManager.GetString("ugovorDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugovor Od.
        /// </summary>
        internal static string ugovorOd {
            get {
                return ResourceManager.GetString("ugovorOd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnici.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visina.
        /// </summary>
        internal static string visina {
            get {
                return ResourceManager.GetString("visina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjede.
        /// </summary>
        internal static string wins {
            get {
                return ResourceManager.GetString("wins", resourceCulture);
            }
        }
    }
}
